export enum AppEvents {
  FETCH_PRODUCTS_LOADING,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_ERROR,
  FETCH_PRODUCT_BY_ID_LOADING,
  FETCH_PRODUCT_BY_ID_SUCCESS,
  FETCH_PRODUCT_BY_ID_ERROR,

  SET_NAME,
  SET_PRICE_EUROS,
  SET_PRICE_CENTS,
  SET_PRICE_PER_KG,
  SET_GLUTEN_FREE,
  SET_LACTOSE_FREE,
  SET_VEGAN,
  SET_DESCRIPTION,
  SET_FILE,
  CLEAR_FORM_VALUES
}
