export enum AppEvents {
  FETCH_PRODUCTS_LOADING,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_ERROR,

  DELETE_PRODUCT_LOADING,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_ERROR,
  DELETE_PRODUCT_LOCALLY,

  SET_NAME,
  SET_PRICE_EUROS,
  SET_PRICE_CENTS,
  SET_PRICE_PER_KG,
  SET_GLUTEN_FREE,
  SET_LACTOSE_FREE,
  SET_VEGAN,
  SET_DESCRIPTION,
  SET_FILE,
  CLEAR_FORM_VALUES,

  POST_PRODUCT_LOADING,
  POST_PRODUCT_SUCCESS,
  POST_PRODUCT_ERROR,
  ENABLE_SUBMIT,
  DISABLE_SUBMIT
}
